# Site settings
title: The Schmear Campaign
email: letsnosh@theschmearcampaign.com
description: "Bagels are holes with rolls around them, but they are quite delicious."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.theschmearcampaign.com" # the base hostname & protocol for your site

source: _source
destination: _public

# Build settings
markdown: kramdown
