# Site settings
title: The Brew Campaign
email: 
description: "Occasional dispatches from Colorado breweries"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://brewcampaign.harmsboone.org" # the base hostname & protocol for your site

ratingscale:
  - Disappointing
  - Meh
  - Decent
  - Good
  - Life-changing

destination: _public

# Build settings
markdown: kramdown

prose:
  rooturl: "_posts"
